### ISSUE TITLE
Add Code of Conduct to the Repository

### ISSUE THREAD

**Issue by swaindhruti** [swaindhruti/First-Commit#2]
### **Issue Description:**
To maintain an inclusive and respectful environment for contributors, we need to add a Code of Conduct to the First Commit repository.

### **Tasks:**

1. Create a `CODE_OF_CONDUCT.md` file in the root of the repository.
2. Use the Contributor Covenant as a template, or any other suitable open-source code of conduct.
3. Ensure that the Code of Conduct is referenced in the README under the Code of Conduct section.

### **References:**
[Contributor Covenant](https://www.contributor-covenant.org/)

**Comment by DeathwingIN** [comment]
Can you assign me to this issue

**Comment by swaindhruti** [comment]
Hello @DeathwingIN,
The issue has been assigned to you can start working on it.

**Comment by swaindhruti** [comment]
Resolved by PR #7
